#!/usr/bin/env bash

# Bootstrapping

if [[ $(uname) == 'Linux' ]]; then
	if [[ $(which apt) == '' ]]; then
		echo 'Must be an Ubuntu-based distribution: missing apt'
		exit 1
	elif [[ $(which snap) == '' ]]; then
		echo 'Must support snap apps: missing snap/snapd'
		exit 1
	fi

	# Install Homebrew for Linux
	sudo apt install build-essential curl file git
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

	# Further config for Homebrew as recommended
	echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >>~/.profile
	eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
	brew install gcc

	# Install planck via apt, rather than planck, because of some errors I've
	# been getting
	sudo add-apt-repository ppa:mfikes/planck
	sudo apt update
	sudo apt install planck
elif [[ $(uname) == 'Darwin' ]]; then
	# Install Homebrew
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	brew install planck
fi

planck ./link-dotfiles.cljs
