;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        delete-indentation
        electric-newline-and-maybe-indent
        indent-for-tab-command
        isearch-abort
        isearch-forward-regexp
        isearch-printing-char
        kill-region
        paredit-backward-kill-word
        paredit-close-curly
        paredit-close-round
        paredit-doublequote
        paredit-forward
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        paredit-reindent-defun
        paredit-splice-sexp
        paredit-splice-sexp-killing-forward
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        backward-kill-sentence
        end-of-buffer
        ido-find-file
        ido-switch-buffer
        mouse-drag-vertical-line
        paredit-forward-delete
        paredit-splice-sexp-killing-backward
        ))
